FROM node:7.2.0

RUN npm install -g elm@0.18.0
RUN npm install -g elm-live

ENV INSTALL_PATH /app

RUN mkdir $INSTALL_PATH
WORKDIR $INSTALL_PATH

COPY . $INSTALL_PATH

CMD elm-live src/Main.elm --yes --debug --warn --host=0.0.0.0 --port=8000
